# Generated by Django 6.0.6 on 2026-06-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='missing_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='study_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
