# Generated by Django 6.0.6 on 2026-06-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_missing_skills_userprofile_study_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dream_company',
            field=models.CharField(blank=True, choices=[('SAP', 'SAP'), ('Google', 'Google'), ('Microsoft', 'Microsoft'), ('Amazon', 'Amazon'), ('Oracle', 'Oracle'), ('TCS', 'TCS'), ('Infosys', 'Infosys')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dream_role',
            field=models.CharField(blank=True, choices=[('Full Stack Dev', 'Full Stack Developer'), ('Backend Dev', 'Backend Developer'), ('Frontend Dev', 'Frontend Developer'), ('Cybersecurity Analyst', 'Cybersecurity Analyst'), ('Cloud Engineer', 'Cloud Engineer'), ('Data Scientist', 'Data Scientist')], max_length=100, null=True),
        ),
    ]
