# Generated by Django 6.0.6 on 2026-06-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_dream_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume_score',
            field=models.CharField(blank=True, help_text='Letter grade (A+, B-, etc.)', max_length=2, null=True),
        ),
    ]
